P_1/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("entry/<str:title>/", views.entry, name = "entry"),
    path("search/", views.search, name = "search"),
    path("search_results/<str:searched>", views.search_results, name = "search_results"),
    path("create/", views.create_page, name = "create_page"),
    path("edit/<str:title>/", views.edit_page, name = "edit_page"),
    path("random/", views.random_page, name = "random_page")
]

P_1/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

P_1/encyclopedia/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

P_1/encyclopedia/forms.py
from django import forms


class SearchForm(forms.Form):
    searched_entry = forms.CharField(max_length=120, label = '', widget=forms.TextInput(attrs={
        'placeholder': "Search entry"   }))



class EntryForm(forms.Form):
    title = forms.CharField(label = '', widget = forms.TextInput(attrs={
        'placeholder': "Entry title"
    }))
    entry_text = forms.CharField(label = '', widget=forms.Textarea(attrs={
        'placeholder':"Entry text",

    }))




class EditForm(forms.Form):
    entry_text = forms.CharField(label = '', widget=forms.Textarea(attrs={
        'placeholder':"Entry text",
    }))

P_1/encyclopedia/views.py
from django.shortcuts import redirect, render
from .forms import SearchForm, EntryForm, EditForm
from django.urls import reverse
import random

from . import util

search_form = SearchForm()
context = {"search_form":search_form}




def index(request):
    context["entries"] = util.list_entries()
    
    return render(request, "encyclopedia/index.html", context)



def entry(request, title):
    result = util.get_entry(title)
    if result == None:
        context["error"] = "Entry not found"
        return render(request, 'encyclopedia/error.html', context)
    else:
        context["text"] = result
        context["title"] = title
        return render(request, 'encyclopedia/entry.html', context) #using a package 'markdownify' to convert md to HTML format, https://pypi.org/project/markdownify/



def search(request, *args, **kwargs):
    if request.method == "POST":
        searched = request.POST['searched_entry']
        if util.get_entry(searched) is not None:
            return redirect(reverse("encyclopedia:entry", kwargs={'title':searched})) #if found, returns to the entry, passing along the "searched" entry into the url to go to the page of that entry
        else:
            return redirect(reverse("encyclopedia:search_results", kwargs={'searched':searched}))



def search_results(request, searched):
    entries = util.list_entries()
    context["entries"] = list(filter(lambda entry: searched.casefold() in entry.casefold(), entries)) #https://www.geeksforgeeks.org/python-finding-strings-with-given-substring-in-list/
    if not context["entries"]:
        context["error"] = f'No results for "{searched}"'
        return render(request, 'encyclopedia/error.html', context)
    else:
        context["searched"] = searched
        return render(request, "encyclopedia/search_results.html", context)



def create_page(request):
    if request.method == "GET":
        context["entry_form"] = EntryForm()
        return render(request, "encyclopedia/create_page.html", context)
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST['entry_text']
        if util.get_entry(title) is not None:
            context["error"] = "Entry already exists/Entry with that title already already exists"
            return render(request, 'encyclopedia/error.html', context)
        else:
            title.capitalize()
            util.save_entry(title, content)
            return redirect(reverse("encyclopedia:entry", kwargs={'title':title})) 


def edit_page(request, title):
    if request.method == "GET":
        if util.get_entry(title) is not None:
            content = util.get_entry(title)
            context["edit_form"] = EditForm(initial = {
                "entry_text":content})
            context["title"] = title
            return render(request, "encyclopedia/edit_page.html", context)
        else:
            context["error"] = "Entry does not exist"
            return render(request, 'encyclopedia/error.html', context)


    if request.method == "POST":
        
        content = request.POST['entry_text']
        util.save_entry(title, content)
        return redirect(reverse("encyclopedia:entry", kwargs={'title':title})) 



def random_page(request):
    
    entry_list = util.list_entries()
    random_entry = random.choice(entry_list)
    return redirect(reverse("encyclopedia:entry", kwargs={'title':random_entry})) 

P_1/encyclopedia/templates/encyclopedia/create_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Creating An Entry
{% endblock %}

{% block body %}
    <h1>Create Entry</h1>
    <form method = "post" action = "{% url 'encyclopedia:create_page' %}">
        {% csrf_token %}
        {{entry_form.as_p}}
        <input type = "submit", value = "Submit entry">
{% endblock %}

P_1/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Editing {{title}}
{% endblock %}

{% block body %}
    <h1>Editing {{title}}</h1>
    <form method = "post" action = "{% url 'encyclopedia:edit_page' title %}">
        {% csrf_token %}
        {{edit_form.as_p}}
        <input type = "submit", value = "Submit entry">
{% endblock %}

P_1/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% load markdownify %}
{% block title %} {{title|lower|capfirst}} {% endblock %}


{% block body %}
<i style = "text-align:right;"> <a href = {% url 'encyclopedia:edit_page' title%}> Edit page </a></i>
{{ text|markdownify }}


{% endblock %}

P_1/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}
{% block title %} Error {% endblock %}
{% block body %}

<h1>Error</h1>
<h3> {{error}} </h3>


{% endblock %}

P_1/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li> <a href = "{% url 'encyclopedia:entry' entry %}"> {{ entry|capfirst }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}

P_1/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method = "post" action = "{% url 'encyclopedia:search' %}">
                    {% csrf_token %}
                    {{search_form.as_p}}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
               
                {% block body %}

                {% endblock %}
            </div>
        </div>

    </body>
</html>

P_1/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search results
{% endblock %}

{% block body %}
    <h1>Search results for: "{{searched}}"</h1>
    <ul>
        {% for entry in entries %}
                <li> <a href = "{% url 'encyclopedia:entry' entry.casefold %}"> {{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}